# -*- coding:utf-8 -*-
import os
from time import sleep
clear = 'clear'  # OS依存のクリアコマンド(Linux:clear, Windows:cls)
timer = 0.08  # 描画速度(秒)
while 1:
    os.system(clear)
    print("□□□□□□    □\n     □    □\n     □    □\n     □    □\n     □    □\n□□□□□□□□□□□\n□    □     \n□    □     \n□    □     \n□    □     \n□    □□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□□□    □\n     □    □\n     □    □\n     □    □\n     □    □\n□□□□□■□□□□□\n□    □     \n□    □     \n□    □     \n□    □     \n□    □□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□□□    □\n     □    □\n     □    □\n     □    □\n     ■    □\n□□□□■■■□□□□\n□    ■     \n□    □     \n□    □     \n□    □     \n□    □□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□□□    □\n     □    □\n     □    □\n     ■    □\n     ■    □\n□□□■■■■■□□□\n□    ■     \n□    ■     \n□    □     \n□    □     \n□    □□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□□□    □\n     □    □\n     ■    □\n     ■    □\n     ■    □\n□□■■■■■■■□□\n□    ■     \n□    ■     \n□    ■     \n□    □     \n□    □□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□□□    □\n     ■    □\n     ■    □\n     ■    □\n     ■    □\n□■■■■■■■■■□\n□    ■     \n□    ■     \n□    ■     \n□    ■     \n□    □□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□□■    □\n     ■    □\n     ■    □\n     ■    □\n     ■    □\n■■■■■■■■■■■\n□    ■     \n□    ■     \n□    ■     \n□    ■     \n□    ■□□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□□■■    □\n     ■    □\n     ■    □\n     ■    □\n     ■    ■\n■■■■■■■■■■■\n■    ■     \n□    ■     \n□    ■     \n□    ■     \n□    ■■□□□□")
    sleep(timer)
    os.system(clear)
    print("□□□■■■    □\n     ■    □\n     ■    □\n     ■    ■\n     ■    ■\n■■■■■■■■■■■\n■    ■     \n■    ■     \n□    ■     \n□    ■     \n□    ■■■□□□")
    sleep(timer)
    os.system(clear)
    print("□□■■■■    □\n     ■    □\n     ■    ■\n     ■    ■\n     ■    ■\n■■■■■■■■■■■\n■    ■     \n■    ■     \n■    ■     \n□    ■     \n□    ■■■■□□")
    sleep(timer)
    os.system(clear)
    print("□■■■■■    □\n     ■    ■\n     ■    ■\n     ■    ■\n     ■    ■\n■■■■■■■■■■■\n■    ■     \n■    ■     \n■    ■     \n■    ■     \n□    ■■■■■□")
    sleep(timer)
    os.system(clear)
    print("■■■■■■    ■\n     ■    ■\n     ■    ■\n     ■    ■\n     ■    ■\n■■■■■■■■■■■\n■    ■     \n■    ■     \n■    ■     \n■    ■     \n■    ■■■■■■")
    sleep(timer)

